### PR TITLE
STYLE: Upgrade python syntax to 3.6 and newer

### PR DESCRIPTION
**Pull request by jamesobutler**
This PR uses [`pyupgrade`](https://github.com/asottile/pyupgrade) to automatically upgrade python syntax to newer versions. The script listed below was run for Python 3.6+ syntax with changes committed.

## Using pyupgrade

- Install: `Python -m pip install pyupgrade`
- Running:
  - On 1 file: `Python -m pyupgrade --py36-plus MyPythonFile.py`
  - On multiple files: Here is my pyupgrade-script.py written to automate running pyupgrade across all python files in the repo. It was run by `Python pyupgrade-script.py`.
```python
# pyupgrade-script.py
import os
import subprocess

search_directory = "C:/Users/JamesButler/Documents/GitHub/whitematteranalysis"
for root, _, files in os.walk(search_directory):
    for file_item in files:
        file_path = os.path.join(root, file_item)
        if os.path.isfile(file_path) and file_path.endswith(".py"):
            subprocess.call(["Python", "-m", "pyupgrade", "--py36-plus", file_path])
```

### CODE REVIEW

**Comment by jamesobutler** [comment]
@ljod Could you help with the integration of this work? Thanks!

**Comment by jamesobutler** [comment]
@zhangfanmark Would you be able to help with the integration of this PR? Thanks!

**Comment by ljod** [comment]
Thanks for the PR! I believe Fan has tested it and will help accept it.



Lauren J. O’Donnell, Ph.D.
Associate Professor, Harvard Medical School
1249 Boylston St., Room #210
Boston, Massachusetts 02215
***@***.***


________________________________

**Comment by zhangfanmark** [comment]
Hi! sorry that this was left behind so much.

Thank you @jamesobutler!!!

**Pull request merged**
