### PR TITLE
ENH: Allow specifying the atlas version at download

### PR DESCRIPTION
**Pull request by jhlegarreta**
- STYLE: Remove unnecessary tab on blank line
- ENH: Allow specifying the atlas version at download
- ENH: Download atlas version metadata file

### CODE REVIEW

**Comment by jhlegarreta** [comment]
This is still a very brittle approach:
- If the user renames the atlas folder, then we may no longer know the version of the atlas they are using.
- Every time a new version is uploaded a new entry needs to be added to the `enum` class.

**Comment by jhlegarreta** [comment]
> - If the user renames the atlas folder, then we may no longer know the version of the atlas they are using.

Commit [fddb36e](https://github.com/SlicerDMRI/whitematteranalysis/pull/132/commits/fddb36e5e831bbe07e9c72bf42f58e7da20284b9) should help keeping a record of what was downloaded even if the folder is renamed. But if the file is removed, then we will missing the relevant information.

Further work is needed to improve things, including a proper data versioning system. Left for future work.

**Review by ljod — COMMENTED** [review]
happy to approve this after rebase

**Comment by jhlegarreta** [comment]
> happy to approve this after rebase

Rebased on `master`.

**Review by ljod — APPROVED** [review]

**Pull request merged**
