### PR TITLE
DOC: Specify call to diffusion measurement module in Linux

### PR DESCRIPTION
**Pull request by jhlegarreta**
Specify how the diffusion measurement module must be called in Linux.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Cross-referencing https://discourse.slicer.org/t/no-csv-file-in-diffusionmessurements-folder-in-wma/28439/7

**Comment by ljod** [comment]
please resolve conflicts and check syntax because markup rendering does not work for me

**Comment by jhlegarreta** [comment]
> please resolve conflicts and check syntax because markup rendering does not work for me

Done in 328a191.

**Review by ljod — APPROVED** [review]
thanks

**Pull request merged**
